services:
  - type: web
    name: hand-snake-game
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FIREBASE_TYPE
        fromSecret: FIREBASE_TYPE
      - key: FIREBASE_PROJECT_ID
        fromSecret: FIREBASE_PROJECT_ID
      - key: FIREBASE_PRIVATE_KEY_ID
        fromSecret: FIREBASE_PRIVATE_KEY_ID
      - key: FIREBASE_PRIVATE_KEY
        fromSecret: FIREBASE_PRIVATE_KEY
      - key: FIREBASE_CLIENT_EMAIL
        fromSecret: FIREBASE_CLIENT_EMAIL
      - key: FIREBASE_CLIENT_ID
        fromSecret: FIREBASE_CLIENT_ID
      - key: FIREBASE_AUTH_URI
        fromSecret: FIREBASE_AUTH_URI
      - key: FIREBASE_TOKEN_URI
        fromSecret: FIREBASE_TOKEN_URI
      - key: FIREBASE_AUTH_PROVIDER_CERT_URL
        fromSecret: FIREBASE_AUTH_PROVIDER_CERT_URL
      - key: FIREBASE_CLIENT_CERT_URL
        fromSecret: FIREBASE_CLIENT_CERT_URL
      - key: FIREBASE_API_KEY
        fromSecret: FIREBASE_API_KEY
      - key: FIREBASE_AUTH_DOMAIN
        fromSecret: FIREBASE_AUTH_DOMAIN
      - key: FIREBASE_DATABASE_URL
        fromSecret: FIREBASE_DATABASE_URL
      - key: FIREBASE_STORAGE_BUCKET
        fromSecret: FIREBASE_STORAGE_BUCKET
      - key: FIREBASE_MESSAGING_SENDER_ID
        fromSecret: FIREBASE_MESSAGING_SENDER_ID
      - key: FIREBASE_APP_ID
        fromSecret: FIREBASE_APP_ID